#!/bin/bash


if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo "`basename $0`: Must provide api level, dex, framework directory and classout directory"
    exit -1;
fi
java -jar ~/bin/baksmali.jar -a $1 -x $2 -d $3 -o $4
